### ISSUE TITLE
Various regressions from recent refactorings

### ISSUE THREAD

**Issue by sandersonet** [aptible/dashboard.aptible.com#317]
The refactoring of aptible-sass and ember-cli-aptible-shared has created several regressions that need fixed before our next production deployment. 

* [x] #319 - Form validation indicators look too much like buttons
* [x] #318 - Flash messages are dismissed on route change
* [x] #314 - Resource tabs no longer indicate the current active tab when redirected to new route
* [x] #304 - Sign up flow looks busted
* [x] #308 - User role changes not immediately reflected
* [x] #300 - Payment info styles busted
* [x] #294 - Vhost buttons are busted
* [x] #293 - Resource header styles are busted
* [x] #289 - Adding a vhost is confusing 
* [x] #287 - Add option for internal vhosts
* [x] #281 - Service container counts break when wrapped
* [x] #321 - Provisioning databases cause broken wrapper
* [x] #323 - Databases should reflect provisioning status
* [x] #324 - Update default vhosts to show virtual_domain rather than external_host
* [x] #325 - Environments index not rendering environments correctly
* [x] #326 - Trigger custom event on newly created stacks

Other minor issues:
* [x] DB selector icons are wack

**Comment by sandersonet** [comment]
Fixed by #327
